[package]
name = "family_album"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/Pfarrer/family_album"

[dependencies]
log = "0.4"
env_logger = "0.8.4"
clap = "3.0.0-beta.2"
glob = "0.3.0"

[dependencies.rusqlite]
version = "0.25.1"

[dev-dependencies]
tempdir = "0.3"