[package]
name = "family_album"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/Pfarrer/family_album "

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"

[dev-dependencies]
tempdir = "0.3"