name: docker_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker Build & Push for ${{ matrix.architecture }}

#    strategy:
#      matrix:
#        architecture:
#          - linux/arm64
#          - linux/arm/v7

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - run: |
          # Workaround for https://github.com/rust-lang/cargo/issues/8719
          sudo mkdir -p /var/lib/docker
          sudo mount -t tmpfs -o size=10G none /var/lib/docker
          sudo systemctl restart docker

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm/v7
          #${{ matrix.architecture }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        id: cache
#        with:
#          path: /tmp/.buildx-cache/${{ matrix.architecture }}
#          key: ${{ runner.os }}-${{ github.sha }}-${{ matrix.architecture }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buildx and Push
        run: docker buildx build --platform linux/amd64,linux/arm/v7 --push -t pfarrer/fotoboek:latest --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" .


